In [1]:
""" Some simple TensorFlow's ops
Author: Chip Huyen
Prepared for the class CS 20SI: "TensorFlow for Deep Learning Research"
cs20si.stanford.edu
"""
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'

import numpy as np
import tensorflow as tf

C:\Users\home\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
a = tf.constant(2)
b = tf.constant(3)
x = tf.add(a,b)

with tf.Session() as sess:
    writer = tf.summary.FileWriter('./graphs/cons', tf.get_default_graph())
    print(sess.run(x))
writer.close() #close the writer when you're done using it

5


In [3]:
a = tf.constant([2,2], name='a')
b = tf.constant([[0,1], [2,3]], name='b')
x =tf.multiply(a,b, name='dot_product')

with tf.Session() as sess:
    print(sess.run(x))   

[[0 2]
 [4 6]]


In [4]:
x = tf.zeros([2,3], tf.int32)
y = tf.zeros_like(x, optimize=True)
print(y)
print(tf.get_default_graph().as_graph_def())
with tf.Session() as sess:
    y = sess.run(y)

Tensor("zeros_like:0", shape=(2, 3), dtype=int32)
node {
  name: "Const"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 2
      }
    }
  }
}
node {
  name: "Const_1"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 3
      }
    }
  }
}
node {
  name: "Add"
  op: "Add"
  input: "Const"
  input: "Const_1"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "a"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 2
          }
        }
        tensor_content: "\002\000\000\000\

In [5]:
with tf.Session() as sess:
    print(sess.run(tf.linspace(10.0, 13.0, 4)))
    print(sess.run(tf.range(5)))
    for i in np.arange(5):
        print(i)

[10. 11. 12. 13.]
[0 1 2 3 4]
0
1
2
3
4


In [7]:
samples = tf.multinomial(tf.constant([[1.,3.,1.]]), 5)

with tf.Session() as sess:
    for _ in range(10):
        print(sess.run(samples))

[[1 1 1 0 1]]
[[1 1 0 0 1]]
[[0 1 1 2 1]]
[[1 0 0 0 1]]
[[1 1 0 1 1]]
[[1 1 1 1 1]]
[[1 1 1 1 1]]
[[1 1 0 1 1]]
[[1 0 0 1 1]]
[[1 1 1 1 1]]


In [11]:
t_0 = 19
x = tf.zeros_like(t_0) ## 0
y = tf.ones_like(t_0) ## 1

with tf.Session() as sess:
    print(sess.run([x,y]))
    
t_1 = ['apple', 'peach', 'banana']
x = tf.zeros_like(t_1) # 
# y = tf.ones_like(t_1) #TypeError

[0, 1]


In [9]:
t_2 = [[True, False, False],
       [False, False, True],
       [False, True, False]] 
x = tf.zeros_like(t_2) # 2x2 tensor
y = tf.ones_like(t_2) # 2x2 tensor

with tf.Session() as sess:
    print(sess.run([x,y]))
    
    
with tf.variable_scope('meh') as scope:
    a = tf.get_variable('a', [10])
    b = tf.get_variable('b', [100])
    
writer = tf.summary.FileWriter('test', tf.get_default_graph())

[array([[False, False, False],
       [False, False, False],
       [False, False, False]]), array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])]


In [12]:
x = tf.Variable(2.0)
y = 2.0 * (x**3)
z = 3.0 + y**2
grad_z = tf.gradients(z, [x, y])

with tf.Session() as sess:
    sess.run(x.initializer)
    print(sess.run(grad_z))

[768.0, 32.0]
